name: Lint

on:
  push:
  pull_request:

jobs:
  lint-ruff:
    name: Lint with Ruff
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout repository

    - uses: chartboost/ruff-action@v1
      name: Run Ruff
